// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsiq95qJDfJeWZy4P-9WcDHhVE1CLJ5rA',
    appId: '1:799738723094:android:28eabec7d3b2a5b2afae37',
    messagingSenderId: '799738723094',
    projectId: 'customer-care-83b73',
    storageBucket: 'customer-care-83b73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Yi5LbVlACewwxRHfui27D1EEyrnD6nU',
    appId: '1:799738723094:ios:5cfa8a593b74ba66afae37',
    messagingSenderId: '799738723094',
    projectId: 'customer-care-83b73',
    storageBucket: 'customer-care-83b73.appspot.com',
    iosClientId:
        '799738723094-1mhbhmirrmsrn03g22h9dm18jtr6i6t3.apps.googleusercontent.com',
    iosBundleId: 'com.customercare',
  );
}
